### ISSUE TITLE
Express Backend

### ISSUE THREAD

**Issue by SVKruik** [SVKruik-Organization/Discord-Bots#51]
#### Requirements

- Backend server for 3rd party interaction.
- Make compatible with Bot Commander.
- Routes in dedicated files.

**Comment by shafinnahian** [comment]
Backend Developer here. Any chance I can be assigned in this issue?

**Comment by SVKruik** [comment]
Hey man! What would you like to build? Have you looked around in the bot files? Would you like to get in touch? @shafinnahian
